---
- name: Install Helm
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Add Helm GPG key
  apt_key:
    url: (link unavailable)
    state: present

- name: Add Helm repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/helm.gpg] (link unavailable) all main"
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install Helm
  apt:
    name: helm
    state: present