---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
    state: present

- name: Add Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
