---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Arch'

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: "Warp | Configure warp"
  ansible.builtin.copy:
    src: themes
    dest: "{{ ansible_user_dir }}/.local/share/warp-terminal/themes/"
    mode: "0644"
    directory_mode: "0755"
    force: true
