---
- name: Install required packages
  apt:
    name: ["wget", "gpg"]
    state: present

- name: Download Warp key
  get_url:
    url: https://releases.warp.dev/linux/keys/warp.asc
    dest: /tmp/warp.asc

- name: Add Warp key to apt keyrings
  shell: gpg --dearmor /tmp/warp.asc > /etc/apt/keyrings/warpdotdev.gpg
  args:
    creates: /etc/apt/keyrings/warpdotdev.gpg

- name: Add Warp repository to sources list
  shell: echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list
  args:
    creates: /etc/apt/sources.list.d/warpdotdev.list

- name: Update apt cache and install Warp Terminal
  apt:
    update_cache: true
    name: warp-terminal
    state: present
