---
- name: Download Debian package
  ansible.builtin.get_url:
    url: "https://app.warp.dev/download?package=deb"
    dest: "/tmp/{{ ansible_date_time.epoch }}.deb"

- name: Install Debian package
  ansible.builtin,apt:
    deb: "/tmp/{{ ansible_date_time.epoch }}.deb"
    state: present
  become: true
