---
- name: Ensure fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory
    mode: '0644'

- name: Download and install Hack Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ ansible_env.HOME }}/.fonts/Hack.zip"
    mode: '0644'

- name: Download and install Hack Nerd Font
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/.fonts/Hack.zip"
    dest: "{{ ansible_env.HOME }}/.fonts/"
    remote_src: true
  register: hack_installed

- name: Remove zip file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts/Hack.zip"
    state: absent
  when: hack_installed is succeeded
