---
- name: "Zsh | {{ ansible_distribution }} | Install Zsh"
  community.general.pacman:
    name: zsh
    state: present
  become: true

- name: "Dot Files | Copy Dot Files"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.zsh/{{ dof_files_item.key }}"
    content: "{{ dof_files_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: dof_files_item
  with_items: "{{ dof_files | default({}) | dict2items }}"
