---
- name: "ZSH | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ZSH_distribution_config

- name: "ZSH | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ZSH_distribution_config.stat.exists

- name: "ZSH | Configure ZSH"
  ansible.builtin.copy:
    src: files/zsh/
    dest: "{{ ansible_user_dir }}/.zsh/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "ZSH | Configure ZSH"
  ansible.builtin.copy:
    src: files/.zshrc
    dest: "{{ ansible_user_dir }}/"
    mode: "0644"
    directory_mode: "0755"
    force: true    

- name: "ZSH | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
