---
- name: Install Brave Browser with Flatpak
  become: true
  flatpak:
    name: com.brave.Browser
    state: present
  flatpak_repo:
    name: flathub
    state: present
  package:
    name: flatpak
    state: present