---
# File: roles/brave_browser/tasks/main.yml
- name: Install Brave Browser with Flatpak
  become: true
  - name: Install flatpak
    package:
      name: flatpak
      state: present

  - name: Add flathub repository
    flatpak_repo:
      name: flathub
      state: present

  - name: Install Brave Browser
    flatpak:
      name: com.brave.Browser
      state: present