---
# File: roles/brave_browser/tasks/main.yml
- name: Install flatpak
  package:
    name: flatpak
    state: present

- name: Install Brave Browser
  community.general.flatpak:
    name: com.brave.Browser
    state: present
    method: system