---
# - name: Create keyrings directory
#   ansible.builtin.file:
#     path: /etc/apt/keyrings
#     state: directory
#     mode: '0644'
#   become: true

# - name: Download GPG key
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
#     dest: /etc/apt/keyrings/gierens.gpg
#     mode: "0644"
#   become: true


- name: Add eza GPG key
  ansible.builtin.apt_key:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    state: present
  become: true

- name: Add Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de/stable/main
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install EZA
  ansible.builtin.apt:
    name: eza
    state: present
  become: true
