---
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0644'
  become: true

# - name: Download GPG key
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
#     dest: /etc/apt/keyrings/gierens.gpg
#     mode: "0644"
#   become: true

- name: Install GPG key
  ansible.builtin.shell: yes | wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  become: true

- name: Add repository
  ansible.builtin.lineinfile:
    dest: /etc/apt/sources.list.d/gierens.list
    line: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
    mode: "0644"
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install EZA
  ansible.builtin.apt:
    name: eza
    state: present
  become: true