---
- name: Download Starship installer script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/install.sh
    mode: "0755"
  register: download_result
  ignore_errors: true

- name: Install Starship if not already installed
  ansible.builtin.command: /tmp/install.sh -y
  args:
    creates: /usr/local/bin/starship
  notify: Configure Starship
