---
- name: Download and install Starship
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/install.sh
    mode: '0755'

- name: Install  Starship
  shell: /tmp/install.sh
  args:
    creates: /usr/local/bin/starship

- name: "Starship | Configure Starship"
  ansible.builtin.copy:
    src: files
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
