---
- name: Download Bitwarden Debian package
  ansible.builtin.get_url:
        url: "https://vault.bitwarden.com/download/?app=desktop&platform=linux"
        dest: "/tmp/bitwarden.pkg.tar.zst"
  delegate_to: localhost

- name: Install Bitwarden Debian package
  community.general.pacman:
    name: "/tmp/bitwarden.pkg.tar.zst"
    state: present
