---
# - name: Download Bitwarden Debian package
#   ansible.builtin.get_url:
#     url: "https://vault.bitwarden.com/download/?app=desktop&platform=linux"
#     dest: "/tmp/bitwarden.AppImage"
- name: Install Bitwarden Flatpak
  command: flatpak install --noninteractive bitwarden